apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: example-qemu
spec:
  accepted: false
  cluster: crash-lab
  node: crash-lab
  pool: crash-lab
  config:
    sockets: 2
    cores: 4
    agent: true
    test: test
