{{- range $qemu, $qemuData := $.Values.qemu }}

{{- range $i, $e := until ($qemuData.count | int) }}
apiVersion: proxmox.xfix.org/v1alpha1
kind: Qemu
metadata:
  name: {{ printf "%s-%d" $qemu $i }}
  finalizers:
    - resources-finalizer.proxmox-operator.xfix.org
spec:
  {{- $qemuData.spec | toYaml | nindent 2 }}
---
{{- end }}

{{- end }}
