qemu:
  masters:
    count: 3
    spec:
      clone: ubuntu-template
      cluster: pve-test
      #node: crash-lab
      #vmid: 222
      pool: prod
      anti-affinity: masters
      autostart: true
      autostop: true
      cpu:
        sockets: 1
        cores: 1
      memory:
        size: 2048
        balloon: 2048
      tags:
        - test1
        - test2
        - test3
  ingress:
    count: 0
    spec:
      cluster: pve-test
      #node: crash-lab
      #vmid: 222
      pool: prod
      anti-affinity: ingress
      autostart: true
      autostop: true
      cpu:
        sockets: 1
        cores: 1
      memory:
        size: 2048
        balloon: 2048
  workers:
    count: 0
    spec:
      cluster: pve-test
      #node: crash-lab
      #vmid: 222
      pool: prod
      #anti-affinity: masters
      autostart: true
      autostop: true
      cpu:
        sockets: 1
        cores: 1
      memory:
        size: 2048
        balloon: 2048

defaultSpec:
  spec:
    #cluster: pve-test
    #node: crash-lab
    #vmid: 222
    pool: prod
    anti-affinity: ""
    autostart: false
    autostop: false
    cpu:
      type: host
      sockets: 1
      cores: 1
    memory:
      size: 1024
      balloon: 1024
    network:
      net0:
        model: virtio
        #mac: A2:7B:45:48:9C:E6
        bridge: vmbr0
        tag: 103
    disk:
      scsi0:
        storage: local-lvm
        size: 3G
    options:
      ostype: "l26"
      bios: "seabios"
      smbios1: "uuid=3ae878b3-a77e-4a4a-adc6-14ee88350d36,manufacturer=MTIz,product=MTIz,version=MTIz,serial=MTIz,sku=MTIz,family=MTIz,base64=1"
      scsihw: "virtio-scsi-pci"
      boot: "order=net0;ide2;scsi0"
      ide2: "none,media=cdrom"
      hotplug: "network,disk,usb"
      tablet: 1
      onboot: 0
      kvm: 1
      agent: "0"
      numa: 0
      protection: 0
      #lol: lol
